apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "graph-db-eval.fullname" . }}
  labels:
    {{- include "graph-db-eval.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "graph-db-eval.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "graph-db-eval.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "graph-db-eval.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: {{ .Values.dataVolume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.dataVolume.claimName }}
        - name: {{ .Values.logVolume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.logVolume.claimName }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: {{ .Values.dataVolume.name }}
              mountPath: {{ .Values.dataVolume.mountPath }}
            - name: {{ .Values.logVolume.name }}
              mountPath: {{ .Values.logVolume.mountPath }}
          command:
            - 'uvicorn'
          args:
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "{{ .Values.service.target_port }}"
            - "--workers"
            - "4"
            - "src.server:APP"
{{/*          command: [ '/bin/sh' ]*/}}
{{/*          args: [ '-c', 'sleep infinity' ]*/}}
          env:
            - name: 'KUZU_DB_PATH'
              value: {{ .Values.dataVolume.mountPath }}
            - name: "LOG_LEVEL"
              value: "10"
            - name: "LOG_PATH"
              value: {{ .Values.logVolume.mountPath }}
          ports:
            - name: http
              containerPort: {{ .Values.service.target_port }}
              protocol: TCP
{{/*          livenessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /docs*/}}
{{/*              port: {{ .Values.service.target_port }}*/}}
{{/*          readinessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /docs*/}}
{{/*              port: {{ .Values.service.target_port }}*/}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
