# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
# SPDX-FileCopyrightText: 2023 Renaissance Computing Institute. All rights reserved.
# SPDX-FileCopyrightText: 2024 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

{{ if .Values.dataVolume.create }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.dataVolume.name }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
  - {{ .Values.dataVolume.accessMode }}
  resources:
    requests:
      storage: {{ .Values.dataVolume.size }}
{{ end }}

{{ if .Values.logVolume.create }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.logVolume.name }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
  - {{ .Values.logVolume.accessMode }}
  resources:
    requests:
      storage: {{ .Values.logVolume.size }}
{{ end }}
