apiVersion: v1
kind: Service
metadata:
  name: {{ include "graph-db-eval.fullname" . }}
  labels:
    {{- include "graph-db-eval.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.target_port }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.https }}
      targetPort: {{ .Values.service.target_port }}
      protocol: TCP
      name: https
  selector:
    {{- include "graph-db-eval.selectorLabels" . | nindent 4 }}
